spring:
  config:
    activate:
      on-profile: dev
  boot:
    admin:
      client:
        url: http://192.168.1.17:8083
  datasource:
    url: jdbc:mysql://192.168.1.7:3306/dsa
    username: root
    password: Admin@123
  kafka:
    producer:
      bootstrap-servers: 192.168.1.7:9092
    consumer:
      bootstrap-servers: 192.168.1.7:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.17:8761/eureka/


---

spring:
  config:
    activate:
      on-profile: prod
