management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - refresh
  endpoint:
    health:
      show-details: ALWAYS
  tracing:
    enabled: true
    sampling:
      probability: 1.0

---

server:
  port: 8083
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://192.168.1.7:3306/dsa
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  batch:
    jdbc:
      initialize-schema: EMBEDDED
    job:
      enabled: false
  kafka:
    template:
      default-topic: client_info
    producer:
      bootstrap-servers: 192.168.1.7:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true


app:
  prop:
    client-csv-file-path: /home/sriban/Workspace/client.csv