management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: ALWAYS
  tracing:
    enabled: true
    sampling:
      probability: 1.0
---

server:
  port: 8761
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: discovery-server
eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    fetch-registry: false
    register-with-eureka: false
#    serviceUrl:
#      defaultZone: http://192.168.1.14:8761/eureka/
name: sriban
dep: be
---

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: discovery-server
eureka:
  client:
    healthcheck:
      enabled: true
    fetch-registry: false
    register-with-eureka: false
