management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: ALWAYS
  tracing:
    enabled: true
    sampling:
      probability: 1.0
---
server:
  port: 8761
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: discovery-server
eureka:
  client:
    healthcheck:
      enabled: true
    fetch-registry: false
    register-with-eureka: false

---

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: discovery-server
eureka:
  client:
    healthcheck:
      enabled: true
    fetch-registry: false
    register-with-eureka: false
